### ISSUE TITLE
Add ability to process subset of images

### ISSUE THREAD

**Issue by adambom** [kvendrik/responsive-images.js#11]
Right now, `makeImagesResponsive` processes every single image in the document, which is inefficient when you have a lot of images on the page and you only want to process one or a few of them.

My proposal is to add a parameter to `makeImagesResponsive` that allows the program to specify which images should be processed. It should default to processing all of them as it does now.

I think it would make sense to allow a querySelector string, which would basically be an argument to `document.querySelector` or its equivalent, or an array of DOM elements for each image you want to transform.

```
makeImagesResponsive('#image');
makeImagesResponsive('.image');
makeImagesResponsive([document.getElementById('image')]);
```

Here is a link to the relevant polyfills required to support `querySelector` and `querySelectorAll`

https://github.com/inexorabletash/polyfill/blob/master/polyfill.js#L671

**Comment by kvendrik** [comment]
Hi @adambom,

First of all, thanks for contributing. :+1:

To be precise: It gets every `img` tag in the document and then processes the ones that have a `data-src` or `data-src2x` attribute. The inefficient part about this is that it also loops through the images that don't have the attribute to check if they have one.

I will run some benchmarks to see if the current approach if faster or using a querySelector. :)

**Comment by adambom** [comment]
@kvendrik to be more specific, the use case I'm thinking of is a long list of images, all with the `data-src` attribute defined. When the user reaches the end of the list, we load more results, and insert another set of images at the bottom of the page (think infinite scroll).

When I call `makeImagesResponsive`, it would be nice if I could run it for only the new images, rather than the many images at the top that have already been processed.

Using `querySelector` may give marginal speed benefits vs. looping through all `img` tags, but the point is to be more specific about which images to target in the first place.

**Comment by kvendrik** [comment]
Ah I get what your saying, you're primarily talking about targeting new images without having to loop through the old ones in a second run. Good point, I'll definitely look into that. A querySelector sounds like it might be a good solution. :)
