### ISSUE TITLE
IE and FF has horizontal scrollbar

### ISSUE THREAD

**Issue by emage** [kvendrik/responsive-images.js#18]
When testing the demo here in a web browser, At smaller resolution, IE and FireFox have a horizontal scrollbar due to the image not fitting the viewport.  Chrome looks great!

**Comment by kvendrik** [comment]
Hey @emage,
Thanks for pointing that out! But thats actually quite alright, the purpose of the demo is just to show that the script loads different images based on the viewport size. Might give the image a max-width next time I'm working on the demo though.
