### ISSUE TITLE
(:) vs. (|)

### ISSUE THREAD

**Issue by abouolia** [kvendrik/responsive-images.js#2]
Better to use (|) instead of the mark (:) because it mixes things when it is inserted in this code

<pre><Code>&lt;img data-src-base='http://demo/images/' data-src='&lt;480:smallest.jpg' /&gt;</code></pre>

or

<pre><code>&lt;img data-src='&lt;480:http://dir' /&gt;</code></pre>

because of the presence of mark (:) in http:// .

**Comment by kvendrik** [comment]
Hi abouolia,

Thanks for bringing this up. I am aware of this issue and will fix it later today by only splitting the string at the first occurance of : .
