### ISSUE TITLE
using a debounced version of makeImageResponsive upon resize event

### ISSUE THREAD

**Issue by mov37** [kvendrik/responsive-images.js#4]
Hi @kvendrik I love the way of how this plugin works, I think it would be nice and a performance boost using a debounced version of makeImageReponsive when browser resizes, like this one http://own.li/BAHt, what do you think?

**Comment by kvendrik** [comment]
Hey 623HS,

Sounds like a great plan. I will look into this further tonight and keep you up-to-date. :)

**Comment by kvendrik** [comment]
How about something with only executing the event when the resize is finished but the con here would be that the visitor might see a blurry picture until he finishes the resize since if the picture is smaller it will stretches to the window's size.

**Comment by fleshgordo** [comment]
There's any easy to use jquery debounced library which you could include: http://www.paulirish.com/2009/throttled-smartresize-jquery-event-handler/

**Comment by kvendrik** [comment]
Hey @fleshgordo ,

Looks great and I'm aware of that but that would require jQuery the be imported in order for the plugin to work.

I'll look into it and see if I can find a native js solution. :)

**Comment by fleshgordo** [comment]
Sorry, forgot about the native js thing.. but this solution should work, right? : http://unscriptable.com/2009/03/20/debouncing-javascript-methods/

**Comment by kvendrik** [comment]
@fleshgordo Hey, Thanks that looks great. I'll have a look at implanting that as soon as possible. :)

**Comment by adambom** [comment]
Probably throttling is more appropriate than debouncing, yes?

**Comment by kvendrik** [comment]
Thanks guys, forgot to include the issue number in the commit message but [here](https://github.com/kvendrik/responsive-images.js/commit/afea9804e63a7a0796ab96c0846867130ef31308) is the commit that fixes this issue.
