### ISSUE TITLE
Images added server side (after page load) don't load until browser window size is changed

### ISSUE THREAD

**Issue by justinbhayes** [kvendrik/responsive-images.js#5]
Is there a way to fire the function makeImagesResponsive after responsive images are loaded onto the page via server side? I'm hoping to fire the makeImagesResponsive function onclick with a possible delay after the images are triggered to load via server side.

**Comment by kvendrik** [comment]
Hi @justinbhayes,

You can call the function on any event you would like. By default the function is called onload and onresize. You can remove or edit these event listeners on the bottom of the responsive-img.js file. 

Let me know if it worked and if you have any other questions. :)

**Comment by justinbhayes** [comment]
I was able to get the images to load by setting a delay from within another function. Thanks!

setTimeout(function () {
            makeImagesResponsive();
        }, 2000);

**Comment by kvendrik** [comment]
Ah great. Can you give some more information on what you are using etc so I can add it to the readme file for reference? :)

**Comment by justinbhayes** [comment]
I can pass along the page url (once live) if you want. Otherwise it might be helpful to note that for a use case of when loading images server side after page load using your script, to call the makeImagesResponsive function (possibly with delay) in the same event that loads in the images. Hopefully that makes sense.

**Comment by kvendrik** [comment]
Hi @justinbhayes,

Thanks! Can you also give a bit more information about how you are applying the script, what you are using (nodejs?). Just a bit I can put into the readme file so people who want to use it with images they get from the server-side know how to use it.
