### ISSUE TITLE
License

### ISSUE THREAD

**Issue by samwalshnz** [kvendrik/responsive-images.js#7]
Hi there,

I would love to use this for a commercial product. Would you be able to add a license file to this repo? And would it be ok to use this for commercial use?

Thanks in advance and great stuff mate!
Sam

**Comment by kvendrik** [comment]
Hi Sam.

Good point, the script is licensed under the MIT license. I will also add this to the top of the script file. Shortly said: it would be an honor if you'd use it. :)
